### PR TITLE
Fix build if cli path contains spaces

### PR DESCRIPTION
**Pull request by cgytrus**

### CODE REVIEW

**Comment by matcool** [comment]
is this really needed? cmake should already deal with it
(this is without the pr changes)
image

**Comment by HJfod** [comment]
image

**Comment by matcool** [comment]
cant repro.. theres also like 10 other uses of ${GEODE_CLI} like that if you really wanted to fix it

**Comment by HJfod** [comment]
I think this is worth merging since it fixes an issue someone had and doesn't break other people's stuff

**Comment by HJfod** [comment]
If this PR fixed Config's issue then yeah apparently

**Comment by cgytrus** [comment]
i have no idea why it breaks in specifically that place specifically for me but adding those quotes indeed fixes the issue for m- what the hell it's working now???? nevermind then i guess, sorry lmao

**Pull request closed without merging**
