### PR TITLE
Fixes and Optimizes Geode to be faster and less buggy

### PR DESCRIPTION
**Pull request by Alphalaneous**
This PR fixes Geode in many ways which will improve the experience of everyone. Every bug has been patched and it has been fully tested.

### CODE REVIEW

**Comment by RoootTheFox** [comment]
can confirm, this made my Geode start so much faster! LGTM

**Comment by SpaghettDev** [comment]
This change is a must need, please merge!

**Comment by CattoDev** [comment]
Goated pr

**Comment by Fleeym** [comment]
I love the fixes made here, on a personal test it improved launch times by 1000%. Can't merge due to conflicts sadly :(

**Comment by TheSillyDoggo** [comment]
yhis will m

**Comment by iristraa** [comment]
i've been looking forward to this pull request, great job on your fantastic work <3 hope to see more groundbreaking prs from you

**Comment by Tiago1257** [comment]
this... changed my life, quite frankly. my geometry dash used to be so slo wnad glitchy andt hen i tested th and i got so good i beat bloodbath in 2 attempt. i finally finished botting eon by ren241 with my favorite aBot and heode did nto crash into a wall and die during 33 minute. i am impressed, amazed, life-changed, mindblown, flabbergasted, shitting and crying of joy all at the same time. this is amazing a nd i hop to c more alp halaneou content in m lief

**Comment by Weebifying** [comment]
this pr changed my life forever

**Comment by SpaghettDev** [comment]
not the time to reminisce about the past weebifying! get back to finding macchew os cocos bindings!!

**Comment by Tiago1257** [comment]
> this pr changed my life forever

you stole this op ninion from me yor'eu bnaned

**Comment by altalk23** [comment]
sadly we decided to be slow and more buggy

**Pull request closed without merging**
