### PR TITLE
Better compression for installer on windows

### PR DESCRIPTION
**Pull request by davidkra230**
This basically just enables solid LMZA compression, makes the compression dictionary size 64mb and, optimizes the data block.

### CODE REVIEW

**Comment by matcool** [comment]
why the 64mb dictionary size may i ask?

**Comment by matcool** [comment]
also why not put this in the installer script itself instead of the cli args

**Comment by matcool** [comment]
41.7mb -> 34.5mb pretty nice

**Comment by davidkra230** [comment]
> why the 64mb dictionary size may i ask?

it usually produces better results when compared to the default 8, the tradeoff is ram used when extracting (64 mb extra instead of 8)

**Review by cgytrus — APPROVED** [review]

**Pull request merged**
