### PR TITLE
Add `geode::prelude` to replace `USE_GEODE_NAMESPACE()`

### PR DESCRIPTION
**Pull request by poweredbypie**
Use a namespace instead of polluting globally with a macro.

### CODE REVIEW

**Comment by HJfod** [comment]
Why is it called `prelude`

**Comment by altalk23** [comment]
@HJfod https://doc.rust-lang.org/reference/names/preludes.html

**Comment by HJfod** [comment]
Huh I see

**Review by matcool — APPROVED** [review]
LGTM (looks gay to me)

**Review by altalk23 — APPROVED** [review]
[uwu](https://github.com/poweredbypie/geode/actions/runs/4388078677/jobs/7684147709
)

**Pull request merged**
