### PR TITLE
String IDs for CustomSongWidget in LevelInfoLayer

### PR DESCRIPTION
**Pull request by Fleeym**
I need those string IDs for a mod I'm creating so I guess I should make a pr for them too.

I'm actually not sure if I did this correctly.

### CODE REVIEW

**Comment by HJfod** [comment]
These IDs should be set in the `CustomSongWidget` class itself and not in `LevelInfoLayer`, make a new file `loader/src/ids/CustomSongWidget.cpp` and hook its init to add the IDs there

**Comment by Fleeym** [comment]
One small problem, CustomSongWidget::init isn't in the bindings

**Comment by HJfod** [comment]
You can add it, its address is `0x685b0` on Windows

**Comment by Fleeym** [comment]
Alright, done

**Comment by HJfod** [comment]
@altalk23 Can you get the MacOS address for `CustomSongWidget::init`? Still gotta add that before merging so the commit can build

**Comment by altalk23** [comment]
its `0x37be20`

**Comment by Fleeym** [comment]
oops i broke something, i'll open another pr

**Pull request closed without merging**
