### PR TITLE
Draft PR for Rust Rewrite

### PR DESCRIPTION
**Pull request by TheBearodactyl**
[sarcastic or not, i WAS in fact told to make a PR for this by one of the main devs, sooooooooo :trollface:](https://github.com/geode-sdk/geode/issues/602#issuecomment-1984341713)

Also, fuck you github, force-pushing does NOT mean I want to close the pull request.

### CODE REVIEW

**Comment by matcool** [comment]
seriously, what is the point of this? we have many, many many reasons as to not do this, ignoring the fact that making a pull request that rewrites an entire project is not a thing any maintainer would ever want.

you can experiment with rust all you want, but opening a PR this early on into development is a bit too enthusiastic, you're **far** from addressing any of the issues we mentioned, because they are far from solvable.

**Comment by TheBearodactyl** [comment]
> seriously, what is the point of this? we have many, many many reasons as to not do this, ignoring the fact that making a pull request that rewrites an entire project is not a thing any maintainer would ever want.
> 
> you can experiment with rust all you want, but opening a PR this early on into development is a bit too enthusiastic, you're **far** from addressing any of the issues we mentioned, because they are far from solvable.

you literally assigned me to do it.

**Comment by Fleeym** [comment]
the rewrite it in rust movement strikes again

**Comment by TheBearodactyl** [comment]
> the rewrite it in rust movement strikes again

We shall oxidize EVERYTHING, nobody is safe.

**Comment by qimiko** [comment]
> as i already said, it would massively improve the readability of code, drastically lower the chance of mods crashing the game, and improve ide integration to near perfection because of how good `rust-analyzer` is.

not disagreeing with the claims, but i think what mat is saying you should have something usable before a pull request is made. in its current state, it's not possible to really evaluate this. for a project like this, you might find better success rewriting parts of it at a time - or at least writing up how you plan on doing this. it's a _really_ big undertaking. talk to someone first before you start this

that being said, it appears that your proposed mod syntax has a good portion of issues that make me worry about your understanding of what's involved here. i would highly recommend getting familiar with the geode codebase, rust, gd modding, c++, etc. before approaching the task of a rewrite. but personally, i don't think what you want is a rewritten codebase. i think you want better rust and c++ interop for writing mods with. that's probably achievable, and definitely less demanding than a full rewrite. keep in mind that a pull request that requires all mods to switch to rust will very likely be denied and probably better suited as a completely different project

**Comment by TheBearodactyl** [comment]
> > as i already said, it would massively improve the readability of code, drastically lower the chance of mods crashing the game, and improve ide integration to near perfection because of how good `rust-analyzer` is.
> 
> not disagreeing with the claims, but i think what mat is saying you should have something usable before a pull request is made. in its current state, it's not possible to really evaluate this. for a project like this, you might find better success rewriting parts of it at a time - or at least writing up how you plan on doing this. it's a _really_ big undertaking. talk to someone first before you start this
> 
> that being said, it appears that your proposed mod syntax has a good portion of issues that make me worry about your understanding of what's involved here. i would highly recommend getting familiar with the geode codebase, rust, gd modding, c++, etc. before approaching the task of a rewrite. but personally, i don't think what you want is a rewritten codebase. i think you want better rust and c++ interop for writing mods with. that's probably achievable, and definitely less demanding than a full rewrite. keep in mind that a pull request that requires all mods to switch to rust will very likely be denied and probably better suited as a completely different project
> 

@
1 - That's why it was a draft pr
2 - Again, that's why it was a draft pr, I'm never in any universe going to rewrite a codebase this big in one go.
3 - the example mod is literally just something i wrote in less than 60 seconds, that is nowhere near being what i actually want it to be like.  
[here's another way of what I'm trying to say](https://youtube.com/clip/UgkxLaqW4qb6FrvNtKw04Dw_94NPS2iVXR23)
4 - In terms of interop, with the way Geode works, full backwards compatibility would pretty much be guaranteed since it's a mod loader first and foremost. As long as it can inject a DLL into GD, it won't really matter what language it's written in.
5 - In terms of avoiding a full rewrite, Geode is already popular enough to the point that even if i do just make a better one from scratch, most people won't want to migrate for convenience sake (which is completely understandable), which would pretty much just render my efforts useless. On the other hand, If i rewrite the Geode codebase instead of making my own thing, more people will install the rust rewrite and more devs will want to rewrite their mods, therefore improving the quality of life for everyone who's using Geode. TL;DR: Making my own thing will render the point of this pr nearly useless, as most people won't use it.

**Comment by TheBearodactyl** [comment]
> > > as i already said, it would massively improve the readability of code, drastically lower the chance of mods crashing the game, and improve ide integration to near perfection because of how good `rust-analyzer` is.
> > 
> > not disagreeing with the claims, but i think what mat is saying you should have something usable before a pull request is made. in its current state, it's not possible to really evaluate this. for a project like this, you might find better success rewriting parts of it at a time - or at least writing up how you plan on doing this. it's a _really_ big undertaking. talk to someone first before you start this
> > 
> > that being said, it appears that your proposed mod syntax has a good portion of issues that make me worry about your understanding of what's involved here. i would highly recommend getting familiar with the geode codebase, rust, gd modding, c++, etc. before approaching the task of a rewrite. but personally, i don't think what you want is a rewritten codebase. i think you want better rust and c++ interop for writing mods with. that's probably achievable, and definitely less demanding than a full rewrite. keep in mind that a pull request that requires all mods to switch to rust will very likely be denied and probably better suited as a completely different project
> > 
> 
> @qimiko 
> 1 - That's why it was a draft pr
> 2 - Again, that's why it was a draft pr, I'm never in any universe going to rewrite a codebase this big in one go.
> 3 - the example mod is literally just something i wrote in less than 60 seconds, that is nowhere near being what i actually want it to be like.  
> [in other words](https://youtube.com/clip/UgkxLaqW4qb6FrvNtKw04Dw_94NPS2iVXR23)
> 4 - In terms of interop, with the way Geode works, full backwards compatibility would pretty much be guaranteed since it's a full mod loader, not just an SDK for writing them. As long as it can inject a DLL into GD, it won't really matter what language it's written in.
> 5 - In terms of avoiding a full rewrite, Geode is already popular enough to the point that even if i do just make a better one from scratch, most people won't want to migrate for convenience sake (which is completely understandable), which would pretty much just render my efforts useless. On the other hand, If i rewrite the Geode codebase instead of making my own thing, more people will install the rust rewrite and more devs will want to rewrite their mods, therefore improving the quality of life for everyone who's using Geode. TL;DR: Making my own thing will render the point of this pr nearly useless, as most people won't use it.

**Pull request closed without merging**
