### PR TITLE
Rename `getChildBySpriteName` to `getChildByFilename`

### PR DESCRIPTION
**Pull request by hiimjustin000**
Let me know if there is anything that needs to be changed

### CODE REVIEW

**Comment by matcool** [comment]
why the rename?

**Comment by hiimjustin000** [comment]
It gets referred to a filename a lot in cocos.

**Comment by matcool** [comment]
imo old name is fine, and this breaks api and abi so not very nice!

**Comment by Piecuuu** [comment]
You could've not renamed it but clone it and then rename it. The old one would just be marked as deprecated so it doesn't break the api.

**Pull request closed without merging**
