### PR TITLE
update cmake shit

### PR DESCRIPTION
**Pull request by TheBearodactyl**

### CODE REVIEW

**Comment by matcool** [comment]
ok two things:
* i think it would be better off just renaming the current win32 to win64, no point in having both given the game only supports 64 bit
* WIN64 is not a real cmake variable, WIN32 covers both arches

**Comment by matcool** [comment]
another thing, renaming to Win64 will most definitely break codegen, since that excepts Win32, so its something we have to deal with there as well :-)

**Comment by TheBearodactyl** [comment]
> ok two things:
> 
> * i think it would be better off just renaming the current win32 to win64, no point in having both given the game only supports 64 bit
> * WIN64 is not a real cmake variable, WIN32 covers both arches

what if people still want to build for earlier versions?

**Comment by TheBearodactyl** [comment]
> another thing, renaming to Win64 will most definitely break codegen, since that expects Win32, so its something we have to deal with there as well :-)

fair point

**Comment by matcool** [comment]
> > ok two things:
> > 
> > * i think it would be better off just renaming the current win32 to win64, no point in having both given the game only supports 64 bit
> > * WIN64 is not a real cmake variable, WIN32 covers both arches
> 
> what if people still want to build for earlier versions?

the geode repo itself is only meant for the latest gd version, things like cocos headers and the stub libraries would have to be changed anyways, which is much more work. they can go back in git history and copy the relevant 32 bit code if they want

**Comment by matcool** [comment]
closing because we already renamed the platform to win64

**Pull request closed without merging**
