### PR TITLE
Make EULA better

### PR DESCRIPTION
**Pull request by NexusSfan**
why did i do this

Improves EULA.
I'm bored.

### CODE REVIEW

**Comment by cursefroge** [comment]
not my blender :( also:
the software IS all the source
i would say keeping "software" for future-proofing
"making it worse or better" is just unnecessary
software doesn't need semi-technical breakdown imo, needs proper terminology too (ex. "index" vs "online collection")
sorry if this comment sounds weird, this just has some issues imo

**Comment by baloogysmoogus** [comment]
balgoogi

**Comment by baloogysmoogus** [comment]
but i baloogysmoogus it what i do @cdc-sys 
im googi baloogi

**Comment by cdc-sys** [comment]
@baloogysmoogus ur not funny, i hope u know that :D

**Comment by baloogysmoogus** [comment]
> @baloogysmoogus do you know DN?

deez nut

**Comment by cdc-sys** [comment]
> > @baloogysmoogus do you know DN?
> 
> deez nut

could you drop ur discord name

**Comment by baloogysmoogus** [comment]
baloogysmoogus

**Comment by matcool** [comment]
not a fan tbh, many terms here dont exist (Core Geode Team), and not a fan of an outsider writing our EULA

**Pull request closed without merging**
