### PR TITLE
Rust Rewrite PR

### PR DESCRIPTION
**Pull request by TheBearodactyl**
[sarcastic or not, i WAS in fact told to make a PR for this by one of the main devs, sooooooooo :trollface:](https://github.com/geode-sdk/geode/issues/602#issuecomment-1984341713)

### CODE REVIEW

**Comment by RayDeeUx** [comment]
> This branch is [3 commits ahead of](https://github.com/TheBearodactyl/geode-rs/compare/geode-sdk%3Ageode%3Amain...rust-rewrite), [2723 commits behind](https://github.com/TheBearodactyl/geode-rs/compare/rust-rewrite...geode-sdk%3Ageode%3Amain) `geode-sdk/geode:main`.
yeah uh

**Comment by TheBearodactyl** [comment]
fuck you github.

**Comment by TheBearodactyl** [comment]
> > This branch is [3 commits ahead of](https://github.com/TheBearodactyl/geode-rs/compare/geode-sdk%3Ageode%3Amain...rust-rewrite), [2723 commits behind](https://github.com/TheBearodactyl/geode-rs/compare/rust-rewrite...geode-sdk%3Ageode%3Amain) `geode-sdk/geode:main`.
> 
> yeah uh

it ain't gonna be done right away my dude

**Comment by TechStudent10** [comment]
honestly good luck

**Comment by TheBearodactyl** [comment]
> honestly good luck 

thanks, gonna need it :D

**Pull request closed without merging**
