### PR TITLE
Brah smaller images

### PR DESCRIPTION
**Pull request by Brahillms**
I used ffmpeg and optipng to make the images/sounds in this repo take up less space.
Saves roughly 1 megabyte.

### CODE REVIEW

**Comment by Brahillms** [comment]
@dankmeme01 bump

**Comment by Brahillms** [comment]
@Cvolton bump

**Comment by Brahillms** [comment]
@HJfod bump

**Comment by RoootTheFox** [comment]
fun fact:
- pinging lead devs will probably make them less likely to merge the PR
- changing files increases the size of the repo even if you're making them smaller
- 1MB is not really worth it imo

**Pull request closed without merging**
