### PR TITLE
Add CCTransitionFade::initWithDuration for mac

### PR DESCRIPTION
**Pull request by ninXout**

### CODE REVIEW

**Review by Cvolton — APPROVED** [review]
I think this is a high quality commit from a high quality pull request and should be accepted as soon as possible so ninXout from Crystal Client can release Crystal Client 4.0.2. In fact I believe the review process should be sped up from its usual procedures, so we do not risk ninXout starting work on Crystal Client 5.0.0 before this pull request gets accepted.

**Comment by cgytrus** [comment]
I think this is a high quality commit from a high quality pull request and should be accepted as soon as possible so ninXout from Crystal Client can release Crystal Client 4.0.2. In fact I believe the review process should be sped up from its usual procedures, so we do not risk ninXout starting work on Crystal Client 5.0.0 before this pull request gets accepted.

**Comment by matcool** [comment]
this commit sucks, dislike,

**Comment by altalk23** [comment]
I think this is a low quality commit from a low quality pull request and should not be accepted as soon as possible so ninXout from Crystal Client can not release Crystal Client 4.0.2. In fact I do not believe the review process should be sped up from its usual procedures, so we risk ninXout starting work on Crystal Client 5.0.0 before this pull request gets accepted.

**Pull request merged**
