### PR TITLE
Optimizing grammar and code perfection

### PR DESCRIPTION
**Pull request by cloudskies13**
idk how to test these code soo...

### CODE REVIEW

**Comment by cloudskies13** [comment]
do i must add using namespace geode? idk

**Comment by CattoDev** [comment]
what the fuck is this pr

**Comment by cloudskies13** [comment]
lol

**Comment by zMidair** [comment]
change the title to "Optimizing grammar and code perfection"

**Comment by cloudskies13** [comment]
sure why not? also going to merge some other things rn

**Comment by TheSillyDoggo** [comment]
so lil optimise removes the menu item crash fix what's the point

**Comment by TheSillyDoggo** [comment]
and you removed m_fields this will crash

**Comment by cloudskies13** [comment]
which commit? as i said i cant test code idk if it crashes?

**Comment by cloudskies13** [comment]
sorry

**Comment by dankmeme01** [comment]
i'll assume this is just a troll pr since this achieves nothing useful.

**Comment by cloudskies13** [comment]
what why this is not a troll pr

**Comment by CattoDev** [comment]
you didn't even test anything, why even make a pr

**Comment by dankmeme01** [comment]
1. removing comments is not optimization
2. removing `m_fields` from field access in modify classes will 100% cause crashes
3. you said yourself you didn't test anything, why even make a PR
4. you removed a lot of code without explaining why
5. you changed the styling of the existing code in a lot of places without a good reason
6. you removed a lot of existing fixes and workarounds for no reason, despite them existing for a very good reason

**Comment by cloudskies13** [comment]
i think you can merge working ones at least

**Comment by Fleeym** [comment]
what is this man smoking

**Comment by RoootTheFox** [comment]
bro's removing essential parts of geode and calls it optimization

**Comment by altalk23** [comment]
i have tried to count the amount of things that will not compile and things that will break and now i am currently getting put inside a crematorium i died of old age at 95 years

**Comment by iristraa** [comment]
mf made the whole pr red like my period blood and call that "contributing"

**Comment by altalk23** [comment]
Adding onto dankmeme's message
7. you literally changed several member names to things that do not exist which in turn will not compile 
8. removing typeinfo casts will crash as explained in the geode docs
9. a ccarray is not iterable, thats the entire reason ccarrayext exists
10. removing default values from member ctors will make them undefined behavior, which is you know bad
11. changing unique ptrs to normal ptrs is bad since they will leak after destructing
12. you straight up removed entire functions like the event listeners which will again make stuff not compile
and this is just 25% of the code i didnt even look at the remaining 75%

**Pull request closed without merging**
